# Sure Daily GitHub - Configuration Example
# This file demonstrates all available configuration options including
# randomization and multi-repository features

# ========================================
# General Settings
# ========================================
general:
  timezone: "UTC"
  mode: "commit"           # "commit" or "issue"
  dryRun: false            # Test mode without actual commits

  # Daily target can be:
  # 1. A fixed number: dailyTarget: 5
  # 2. A range: dailyTarget: { min: 12, max: 50 }
  dailyTarget: 1           # Fixed count (1-100)
  # dailyTarget:           # Range-based (alternative)
  #   min: 12
  #   max: 50

# ========================================
# Randomization Settings (Optional)
# ========================================
# Uncomment to enable randomization features
# randomization:
#   enabled: true
#
#   # Override issue count with specific range
#   issueCount:
#     min: 12
#     max: 50
#
#   # Time-based variations (optional)
#   timeVariations:
#     enabled: true
#
#     # Per-hour limits
#     hourly:
#       min: 1
#       max: 5
#
#     # Per-day limits
#     daily:
#       min: 10
#       max: 30
#
#     # Per-week limits
#     weekly:
#       min: 50
#       max: 150

# ========================================
# Repository Selection Strategy (Optional)
# ========================================
# Uncomment to enable custom repository selection
# repositorySelection:
#   # Strategy: "sequential", "random", "weighted", "round-robin"
#   strategy: "sequential"
#
#   # Randomize the order each execution
#   randomizeOrder: false
#
#   # Max repositories per execution (null = all)
#   maxPerExecution: null

# ========================================
# Scheduler Configuration
# ========================================
schedule:
  enabled: false           # Enable automatic scheduling
  cron: "0 */6 * * *"     # Every 6 hours
  timezone: "UTC"

  # Common cron patterns:
  # */3 * * * *      - Every 3 minutes
  # */5 * * * *      - Every 5 minutes
  # 0 * * * *        - Every hour
  # 0 */2 * * *      - Every 2 hours
  # 0 */6 * * *      - Every 6 hours
  # 0 9 * * *        - Daily at 9 AM
  # 0 9,17 * * *     - Twice daily (9 AM and 5 PM)

# ========================================
# Repositories
# ========================================
repositories:
  # Basic example
  - owner: "yourusername"
    repo: "your-repo"
    enabled: true
    branch: "main"
    dailyTarget: 1
    path: "daily-updates"  # For commit mode
    commitMessage: "docs: daily update ${date}"
    labels: ["automated"]  # For issue mode
    weight: 1              # For weighted selection

  # Example with range-based target
  # - owner: "yourusername"
  #   repo: "another-repo"
  #   enabled: true
  #   branch: "main"
  #   dailyTarget:
  #     min: 5
  #     max: 15
  #   weight: 40
  #   labels: ["automated", "high-priority"]

  # Example with higher weight
  # - owner: "yourusername"
  #   repo: "important-repo"
  #   enabled: true
  #   branch: "main"
  #   dailyTarget: 10
  #   weight: 50
  #   labels: ["automated", "critical"]

# ========================================
# Content Template
# ========================================
contentTemplate:
  # Variables: ${date}, ${time}, ${timestamp}
  title: "Daily Update"
  body: |
    # Daily Progress - ${date}

    Automated daily update for tracking activity.

    ## Status
    - System operational
    - Update created at ${time}

    ---
    Generated at ${timestamp}
